# Generated by Django 4.2.6 on 2023-10-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
