# Generated by Django 4.2.6 on 2023-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_feed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='feeds',
            field=models.ManyToManyField(to='farm.feed'),
        ),
    ]
